version: '3'

# Application-specific tasks for EAS Attestor for Github
vars:
  BUILD_DIR: build
  HTML_DIST_DIR: "{{.BUILD_DIR}}/html/dist"
  REACT_SRC_DIR: "src/main/react"
  REACT_DIST_DIR: "{{.BUILD_DIR}}/react/dist"
  VALIDATOR_SRC_DIR: "src/main/typescript/validator"
  VALIDATOR_BUILD_DIR: "{{.BUILD_DIR}}/typescript/validator"

tasks:
  # Build tasks (application-specific only)
  build:
    desc: Build all application components (HTML dApp, React dApp, and validator)
    deps: [build:schemas, build:server, build:dist, build:react, build:validator]

  build:schemas:
    desc: Generate TypeScript types and EAS schemas from protobuf definitions
    cmds:
      - task protobuf:gen-typescript
      - task: build:openapi
      - echo "✅ TypeScript protobuf types and OpenAPI docs generated"
    sources:
      - src/main/proto/**/*.proto
    generates:
      - src/generated/typescript/**/*.ts
      - src/generated/openapi/**/*.json

  build:openapi:
    desc: Generate OpenAPI/Swagger documentation from protobuf services
    cmds:
      - echo "📚 Generating OpenAPI documentation..."
      - mkdir -p src/generated/openapi
      - |
        cd src/main/proto && buf generate --path attestor/v1/services.proto --template ../../../buf.gen.openapi.yaml --include-imports
      - echo "✅ OpenAPI documentation generated"
    sources:
      - src/main/proto/**/*.proto
    generates:
      - src/generated/openapi/**/*.json

  build:server:
    desc: Generate Express server from OpenAPI specification
    deps: [build:openapi]
    cmds:
      - echo "🚀 Generating Express server from OpenAPI spec..."
      - mkdir -p src/generated/server
      - |
        openapi-generator-cli generate \
          -i src/generated/openapi/attestor_api.swagger.json \
          -g nodejs-express-server \
          -o src/generated/server \
          --additional-properties=packageName=attestor-api-server,packageVersion=1.0.0,modelPropertyNaming=camelCase,enumPropertyNaming=camelCase
      - echo "🔧 Wiring actual service implementations..."
      - cp src/main/typescript/services/rest/SignServiceImpl.js src/generated/server/services/SignServiceService.js
      - cp src/main/typescript/services/rest/AttestServiceImpl.js src/generated/server/services/AttestServiceService.js
      - cp src/main/typescript/services/rest/ContributionServiceImpl.js src/generated/server/services/ContributionServiceService.js
      - echo "🔧 Fixing port configuration to use PORT environment variable..."
      - node scripts/task/app/fix-server-config.cjs
      - echo "🔧 Adding uint64 format validator to express server..."
      - node scripts/task/app/fix-express-server.cjs
      - echo "🔒 Adding security headers to Express server..."
      - node scripts/task/app/add-security-headers.cjs
      - echo "🔧 Adding PascalCase exports for OpenAPI validator..."
      - node scripts/task/app/fix-all-controller-exports.cjs
      - echo "📦 Installing server dependencies..."
      - node scripts/task/app/install-server-deps.cjs
      - echo "✅ Express server generated and wired"
    sources:
      - src/generated/openapi/**/*.json
    generates:
      - src/generated/server/**/*


  build:dist:
    desc: Build HTML dApp for deployment (legacy)
    cmds:
      - mkdir -p {{.HTML_DIST_DIR}}
      - cp -r src/main/html/* {{.HTML_DIST_DIR}}/
      - echo "📋 Copying JSON schema files..."
      - mkdir -p {{.HTML_DIST_DIR}}/json/attestor/v1
      - cp -r src/main/json/* {{.HTML_DIST_DIR}}/json/
      - echo "📋 Copying config files..."
      - mkdir -p {{.HTML_DIST_DIR}}/config
      - cp -r src/main/config/* {{.HTML_DIST_DIR}}/config/
      - |
        # Inject build-time environment variables
        if [ -n "$EAS_VALIDATOR_URL" ]; then
          echo "🔧 Injecting validator URL: $EAS_VALIDATOR_URL"
          sed -i.bak "s|// BUILD_TIME_CONFIG_INJECTION|window.EAS_VALIDATOR_URL = '$EAS_VALIDATOR_URL';|g" {{.HTML_DIST_DIR}}/config.js
          rm {{.HTML_DIST_DIR}}/config.js.bak 2>/dev/null || true
        else
          echo "⚠️  No EAS_VALIDATOR_URL set - using dynamic detection"
        fi
    deps: []
    sources:
      - src/main/html/**/*
      - src/main/json/**/*
      - src/main/config/**/*
    generates:
      - "{{.HTML_DIST_DIR}}/**/*"

  build:react:
    desc: Build React dApp for deployment
    dir: '{{.REACT_SRC_DIR}}'
    deps: [react:install]
    cmds:
      - echo "Building React dApp..."
      - npm run build
      - echo "✅ React dApp built to {{.REACT_DIST_DIR}}"
    sources:
      - src/**/*
      - index.html
      - package.json
      - vite.config.ts
      - tsconfig.json
    generates:
      - "{{.REACT_DIST_DIR}}/**/*"

  build:validator:
    desc: Build validator service with HTML files and generated TypeScript
    deps: [build:schemas, build:dist]
    cmds:
      - echo "🔨 Building validator service..."
      - mkdir -p {{.VALIDATOR_BUILD_DIR}}
      - cp -r {{.VALIDATOR_SRC_DIR}}/* {{.VALIDATOR_BUILD_DIR}}/
      - echo "📄 Copying HTML files to validator build..."
      - cp -r {{.HTML_DIST_DIR}} {{.VALIDATOR_BUILD_DIR}}/html/
      - echo "📋 Copying config and JSON files to HTML root for static serving..."
      - cp -r {{.HTML_DIST_DIR}}/config {{.VALIDATOR_BUILD_DIR}}/html/
      - cp -r {{.HTML_DIST_DIR}}/json {{.VALIDATOR_BUILD_DIR}}/html/
      - echo "📋 Creating environment-agnostic schema config..."
      - |
        if [ "${ENVIRONMENT:-staging}" = "production" ]; then
          cp {{.HTML_DIST_DIR}}/config/schemas-production.json {{.VALIDATOR_BUILD_DIR}}/html/config/schemas.json
        else
          cp {{.HTML_DIST_DIR}}/config/schemas-staging.json {{.VALIDATOR_BUILD_DIR}}/html/config/schemas.json
        fi
      - echo "🔧 Copying generated TypeScript protobuf types..."
      - mkdir -p {{.VALIDATOR_BUILD_DIR}}/generated
      - cp -r src/generated/typescript {{.VALIDATOR_BUILD_DIR}}/generated/
      - echo "📚 Copying OpenAPI documentation..."
      - mkdir -p {{.VALIDATOR_BUILD_DIR}}/html/docs
      - cp -r src/generated/openapi/* {{.VALIDATOR_BUILD_DIR}}/html/docs/ 2>/dev/null || echo "No OpenAPI docs found"
      - echo "📋 Copying schema configuration..."
      - mkdir -p {{.VALIDATOR_BUILD_DIR}}/config
      - cp -r src/main/config/* {{.VALIDATOR_BUILD_DIR}}/config/
      - echo "📦 Installing validator dependencies..."
      - cd {{.VALIDATOR_BUILD_DIR}} && npm install --only=production
      - echo "✅ Validator build complete with HTML files, generated types, docs, and config"
    sources:
      - "{{.VALIDATOR_SRC_DIR}}/**/*"
      - "{{.HTML_DIST_DIR}}/**/*"
      - "src/generated/typescript/**/*"
      - "src/main/config/**/*"
    generates:
      - "{{.VALIDATOR_BUILD_DIR}}/**/*"

  # Application tests (TypeScript)
  test:typescript:
    desc: Run TypeScript unit tests
    cmds:
      - npm test

  test:integration:
    desc: Run local integration tests (service orchestration)
    cmds:
      - npm test -- src/test/typescript/integration/service-orchestration.test.ts

  test:server:integration:
    desc: Run server integration tests (requires local server)
    cmds:
      - echo "🚀 Starting validator service for integration testing..."
      - ./scripts/task/app/validator-bg.sh 6001
      - echo "🧪 Running server integration tests..."
      - VALIDATOR_URL=http://localhost:6001 npm test -- src/test/typescript/integration/server-integration.test.ts || (./scripts/task/app/validator-stop.sh && exit 1)
      - echo "🛑 Stopping validator service..."
      - ./scripts/task/app/validator-stop.sh
      - echo "✅ Server integration tests complete!"


  # Development tasks
  dev:
    desc: Start complete development environment
    cmds:
      - ./scripts/task/app/dev-server.sh

  serve:
    desc: Serve the built dApp locally
    deps: [build:dist]
    cmds:
      - ./scripts/task/app/serve.sh

  serve:bg:
    desc: Serve the dApp in background
    deps: [build:dist] 
    cmds:
      - ./scripts/task/app/serve-bg.sh

  serve:docs:
    desc: Serve OpenAPI documentation with Swagger UI
    deps: [build:openapi]
    cmds:
      - echo "📚 Starting API documentation server..."
      - |
        if command -v swagger-ui-serve &> /dev/null; then
          swagger-ui-serve src/generated/openapi/attestor_api.swagger.json
        else
          echo "📚 API docs available at http://localhost:8082"
          cd src/generated/openapi && python3 -m http.server 8082
        fi

  # Validator service tasks
  validator:install:
    desc: Install validator dependencies
    dir: '{{.VALIDATOR_SRC_DIR}}'
    cmds:
      - echo "Installing validator dependencies..."
      - npm install

  validator:dev:
    desc: Run validator service locally for development
    dir: '{{.VALIDATOR_SRC_DIR}}'
    deps: [validator:install]
    cmds:
      - echo "Starting validator in development mode..."
      - echo "Make sure to copy .env.example to .env and set VALIDATOR_PRIVATE_KEY"
      - node index.js

  validator:bg:
    desc: Start validator service in background for testing
    cmds:
      - ./scripts/task/app/validator-bg.sh 6001

  validator:stop:
    desc: Stop background validator service
    cmds:
      - ./scripts/task/app/validator-stop.sh

  validator:docker:build:
    desc: Build validator Docker image for x86_64 architecture
    deps: [build:validator]
    cmds:
      - echo "Building validator Docker image for linux/amd64..."
      - cp {{.VALIDATOR_SRC_DIR}}/Dockerfile {{.VALIDATOR_BUILD_DIR}}/
      - docker buildx build --platform linux/amd64 -t allenday/attestor:latest {{.VALIDATOR_BUILD_DIR}}
      - echo "Docker image built - allenday/attestor:latest (linux/amd64)"

  validator:docker:push:
    desc: Push validator Docker image to DockerHub
    deps: [validator:docker:build]
    cmds:
      - echo "Pushing validator Docker image to DockerHub..."
      - docker push allenday/attestor:latest
      - echo "Docker image pushed - allenday/attestor:latest"

  validator:docker:run:
    desc: Run validator container locally
    deps: [validator:docker:build]
    cmds:
      - echo "Starting validator container..."
      - docker run --rm -p 5001:5001 --env-file {{.VALIDATOR_SRC_DIR}}/.env attestor:latest

  validator:docker:bg:
    desc: Run validator container in background
    deps: [validator:docker:build]
    cmds:
      - echo "Starting validator container in background..."
      - docker run -d --name attestor -p 5001:5001 --env-file {{.VALIDATOR_SRC_DIR}}/.env attestor:latest
      - echo "Validator running at http://localhost:5001"
      - echo "Use 'task app:validator:docker:stop' to stop"

  validator:docker:stop:
    desc: Stop validator container
    cmds:
      - echo "Stopping validator container..."
      - docker stop attestor || true
      - docker rm attestor || true

  validator:docker:logs:
    desc: Show validator container logs
    cmds:
      - docker logs -f attestor

  validator:health:
    desc: Check validator health
    cmds:
      - echo "Checking validator health..."
      - curl -f http://localhost:5001/health || echo "Validator not responding"

  # React dApp development tasks
  react:install:
    desc: Install React dApp dependencies
    dir: '{{.REACT_SRC_DIR}}'
    cmds:
      - echo "Installing React dApp dependencies..."
      - npm install

  react:dev:
    desc: Run React dApp in development mode
    dir: '{{.REACT_SRC_DIR}}'
    deps: [react:install]
    cmds:
      - echo "Starting React development server..."
      - echo "React app will be available at http://localhost:3000"
      - npm run dev

  react:build:
    desc: Build React dApp for production
    dir: '{{.REACT_SRC_DIR}}'
    deps: [react:install]
    cmds:
      - echo "Building React dApp for production..."
      - npm run build
      - echo "✅ React dApp built successfully"

  react:preview:
    desc: Preview React production build
    dir: '{{.REACT_SRC_DIR}}'
    deps: [react:build]
    cmds:
      - echo "Starting React preview server..."
      - echo "Preview will be available at http://localhost:4173"
      - npm run preview

  react:lint:
    desc: Lint React code
    dir: '{{.REACT_SRC_DIR}}'
    deps: [react:install]
    cmds:
      - echo "Linting React code..."
      - npm run lint

  react:lint:fix:
    desc: Fix React linting issues
    dir: '{{.REACT_SRC_DIR}}'
    deps: [react:install]
    cmds:
      - echo "Fixing React linting issues..."
      - npm run lint:fix

  validator:test:
    desc: Test validation endpoint (requires GITHUB_USERNAME, GIST_URL, ETH_ADDRESS)
    preconditions:
      - sh: '[ -n "{{.GITHUB_USERNAME}}" ]'
        msg: "GITHUB_USERNAME required. Usage: task app:validator:test GITHUB_USERNAME=yourname GIST_URL=https://... ETH_ADDRESS=0x..."
      - sh: '[ -n "{{.GIST_URL}}" ]'
        msg: "GIST_URL required"
      - sh: '[ -n "{{.ETH_ADDRESS}}" ]'
        msg: "ETH_ADDRESS required"
    cmds:
      - echo "Testing validation endpoint..."
      - |
        curl -X POST http://localhost:5001/validate \
          -H "Content-Type: application/json" \
          -d '{
            "githubUsername": "{{.GITHUB_USERNAME}}",
            "gistUrl": "{{.GIST_URL}}",
            "ethereumAddress": "{{.ETH_ADDRESS}}"
          }' | jq .

  dev:stop:
    desc: Stop development environment
    cmds:
      - ./scripts/task/app/stop-dev.sh

  # Docker Compose tasks
  docker:up:
    desc: Start local docker-compose environment
    deps: [build]
    cmds:
      - echo "Starting local docker-compose environment..."
      - cd deploy/local/dev && docker compose up -d
      - echo "Services running at localhost ports 6000 (dApp) and 6001 (validator)"

  docker:down:
    desc: Stop local docker-compose environment
    cmds:
      - echo "Stopping local docker-compose environment..."
      - cd deploy/local/dev && docker compose down

  docker:logs:
    desc: Show docker-compose logs
    cmds:
      - cd deploy/local/dev && docker compose logs -f

  docker:status:
    desc: Show docker-compose status
    cmds:
      - cd deploy/local/dev && docker compose ps

  create-schema:
    desc: Show instructions for creating EAS schema
    cmds:
      - ./scripts/task/app/create-schema.sh {{.NETWORK | default "base-sepolia"}}

  # Format tasks (application-specific only)  
  format:typescript:
    desc: Format TypeScript code
    cmds:
      - npm run format

  # Clean tasks
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}

  # Health check tasks
  doctor:
    desc: Application-specific health checks
    cmds:
      - echo "🏥 Running EAS Attestor for Github health checks..."
      - cmd: node --version
        silent: true
      - echo "✅ Node.js is available"
      - cmd: test -d src/main/html
      - echo "✅ dApp source directory exists"
      - cmd: test -d src/main/typescript/validator
      - echo "✅ Validator service directory exists"
      - cmd: test -f package.json
      - echo "✅ Node.js package file found"
      - cmd: test -f tsconfig.json
      - echo "✅ TypeScript configuration found"
      - echo ""
      - echo "🔐 Checking secret management configuration..."
      - task: :secrets:doctor
      - echo "🎉 All application health checks passed!"


  # Setup tasks
  setup:
    desc: Setup application development environment
    cmds:
      - echo "🚀 Setting up EAS Attestor for Github..."
      - npm install
      - mkdir -p {{.BUILD_DIR}} {{.HTML_DIST_DIR}} {{.VALIDATOR_BUILD_DIR}} deployments state
      - task app:validator:install
      - task app:build
      - echo "✅ Application setup complete!"


  # Kubernetes deployment tasks
  k8s:deploy:staging:
    desc: Deploy complete staging environment (Base Sepolia) with all prerequisites
    env:
      BWS_ACCESS_TOKEN: "${BWS_ACCESS_TOKEN}"
      BWS_PROJECT_ID: "${BWS_PROJECT_ID}"
    cmds:
      - |
        echo "🚀 Deploying staging environment with all prerequisites..."
        
        # Use local kubeconfig for now until BWS token issue is resolved
        KUBECONFIG="../kube-hetzner/k3s_kubeconfig.yaml"
        
        echo "📋 Creating namespaces (idempotent)..."
        kubectl --kubeconfig="$KUBECONFIG" create namespace staging --dry-run=client -o yaml | kubectl --kubeconfig="$KUBECONFIG" apply -f -
        kubectl --kubeconfig="$KUBECONFIG" create namespace production --dry-run=client -o yaml | kubectl --kubeconfig="$KUBECONFIG" apply -f -
        
        echo "🔑 Checking SecretStore configuration..."
        if ! kubectl --kubeconfig="$KUBECONFIG" get secretstore bitwarden-secretstore -n staging >/dev/null 2>&1; then
          echo "Creating missing SecretStore..."
          kubectl --kubeconfig="$KUBECONFIG" apply -f bitwarden-secretstore.yaml
        else
          echo "SecretStore already exists, skipping to avoid disruption"
        fi
        
        echo "📋 Applying ClusterIssuer (prerequisite)..."
        kubectl --kubeconfig="$KUBECONFIG" apply -f deploy/k8s/staging/letsencrypt-clusterissuer.yaml
        
        echo "📋 Applying all staging resources (secrets, service, deployment, ingress)..."  
        kubectl --kubeconfig="$KUBECONFIG" apply -f deploy/k8s/staging/
        
        echo "✅ Deployment complete! Checking status..."
        kubectl --kubeconfig="$KUBECONFIG" get all -n staging
        echo ""
        echo "🔍 SSL Certificate status:"
        kubectl --kubeconfig="$KUBECONFIG" get certificate -n staging
    preconditions:
      - sh: '[ -f "../kube-hetzner/k3s_kubeconfig.yaml" ]'
        msg: "kubeconfig file not found at ../kube-hetzner/k3s_kubeconfig.yaml"
      - sh: '[ -f "bitwarden-secretstore.yaml" ]'
        msg: "SecretStore configuration not found at bitwarden-secretstore.yaml"

  k8s:deploy:production:
    desc: Deploy to Kubernetes production environment (Base mainnet)
    cmds:
      - kubectl apply -f deploy/k8s/production/

  k8s:destroy:staging:
    desc: Destroy Kubernetes staging environment
    cmds:
      - kubectl delete -f deploy/k8s/staging/ || true

  k8s:destroy:production:
    desc: Destroy Kubernetes production environment
    cmds:
      - kubectl delete -f deploy/k8s/production/ || true

  k8s:status:staging:
    desc: Check Kubernetes staging deployment status
    cmds:
      - echo "🔍 Staging environment status (Base Sepolia)"
      - kubectl get all -n staging
      - echo ""
      - kubectl get ingress -n staging

  k8s:status:production:
    desc: Check Kubernetes production deployment status
    cmds:
      - echo "🔍 Production environment status (Base mainnet)"
      - kubectl get all -n production
      - echo ""
      - kubectl get ingress -n production

  k8s:logs:staging:
    desc: Show logs from Kubernetes staging pods
    cmds:
      - kubectl logs -n staging -l app=attestor --tail=100 -f

  k8s:logs:production:
    desc: Show logs from Kubernetes production pods
    cmds:
      - kubectl logs -n production -l app=attestor --tail=100 -f

  k8s:restart:staging:
    desc: Restart Kubernetes staging deployment
    cmds:
      - kubectl rollout restart deployment/attestor -n staging

  k8s:restart:production:
    desc: Restart Kubernetes production deployment
    cmds:
      - kubectl rollout restart deployment/attestor -n production

  k8s:shell:staging:
    desc: Open shell in staging pod
    cmds:
      - kubectl exec -it -n staging deployment/attestor -- /bin/bash

  k8s:shell:production:
    desc: Open shell in production pod
    cmds:
      - kubectl exec -it -n production deployment/attestor -- /bin/bash
